nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmPublishAccess: "public"
npmAuthToken: ${NODE_AUTH_TOKEN || ''}
npmPublishRegistry: "https://registry.npmjs.org"
npmRegistryServer: "https://npm.pkg.github.com"
