nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmPublishAccess: "public"
npmAuthToken: ${NODE_AUTH_TOKEN || ''}
npmPublishRegistry: "https://registry.npmjs.org"
npmRegistries:
  "https://npm.pkg.github.com":
    npmAuthToken: ${NODE_AUTH_TOKEN || ''}
    npmAlwaysAuth: true

npmScopes:
  "@monerium":
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN || ''}
    npmRegistryServer: "https://npm.pkg.github.com"
