nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmPublishAccess: "public"
npmScopes:
  "@monerium":
    npmAuthToken: ${NODE_AUTH_TOKEN || ''}
    npmRegistryServer: "https://npm.pkg.github.com"

supportedArchitectures:
  os:
    - "current"
    - "darwin"
    - "linux"
    - "win32"

  cpu:
    - "current"
    - "x86"
    - "x64"
    - "arm64"
    - "ia32"
