nodeLinker: pnp

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmPublishAccess: "public"

npmScopes:
  monerium:
    npmAlwaysAuth: true
    npmAuthToken: ${NODE_AUTH_TOKEN:undefined}
    npmRegistryServer: "https://registry.npmjs.org"

supportedArchitectures:
  cpu:
    - x64
  libc:
    - glibc
  os:
    - linux
