nodeLinker: node-modules

yarnPath: .yarn/releases/yarn-3.5.0.cjs

npmPublishAccess: "public"
npmScopes:
  "@monerium:":
    npmAuthToken: ${NODE_AUTH_TOKEN || ''}
    npmRegistryServer: "https://npm.pkg.github.com"
