name: Build

on:
  # release:
  #   types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows other workflows to trigger this one
  workflow_call:
    inputs:
      prep_good:
        description: "Prep is good"
        type: string

jobs:
  build-test:
    name: "Do other stuff"
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v3
        with:
          name: static-artifacts
      - name: Extract artifacts
        run: |
          tar -xvf coverage.tar --one-top-level
          tar -xvf docs.tar --one-top-level
        shell: bash
      - run: ls -al
      - run: cd docs && ls
      - run: yarn install --immutable --immutable-cache
      - run:
          yarn test
          # for security reasons, use --check-cache if accepting PRs from third-parties.
        # - run: yarn prepublish
