name: Build

on:
  # release:
  #   types: [created]
  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:
  # Allows other workflows to trigger this one
  workflow_call:
    inputs:
      prep_good:
        description: "Prep is good"
        type: string

jobs:
  do-stuff:
    name: "Do other stuff 2"
    runs-on: ubuntu-latest
    steps:
      - name: "Download Artifact"
        uses: actions/download-artifact@v3
        with:
          name: static-folder
      - run: ls -al
      - run:
          cd static && ls

          # for security reasons, use --check-cache if accepting PRs from third-parties.
        # - run: yarn prepublish
