name: Running Code Coverage

on: [push]

jobs:
  needs: deploy_docs
  deploy_coverage:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [18.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Set up Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: yarn install

      - name: Run the tests
        run: yarn test:coverage
      - name: Deploy coverage 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: coverage # The folder the action should deploy.
          COMMIT-MESSAGE: "Deployed SDK Docs to Github Pages (https://monerium.github.io/sdk/coverage)"
          TARGET-FOLDER: coverage
