#
# Builds the docs and deploys to GitHub pages
#
# https://github.com/actions/setup-node
# Using https://github.com/marketplace/actions/deploy-to-github-pages
name: Deploy to TypeDoc to Github pages

on:
  push:
    #tags:
    #  - v*
    branches:
      - main
      - vite

jobs:
  deploy_pages:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: "18"
          cache: "yarn"
      - run: yarn install
      - run: yarn docs
      - run: touch docs/.nojekyll
      - name: Deploy docs 🚀
        uses: JamesIves/github-pages-deploy-action@v4.2.5
        with:
          TOKEN: ${{ secrets.GITHUB_TOKEN }}
          BRANCH: gh-pages # The branch the action should deploy to.
          FOLDER: docs # The folder the action should deploy.
          CLEAN: true # Automatically remove deleted files from the deploy branch
          COMMIT-MESSAGE: "Deployed SDK Docs to Github Pages (https://monerium.github.io/sdk)"
