name: Release Please

on:
  push:
    branches:
      - ci-test
jobs:
  release-please:
    name: "Create release"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        # if: ${{ steps.release.outputs.release_created }}
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          registry-url: "https://registry.npmjs.org"
          # cache: "yarn"

        # if: ${{ steps.release.outputs.release_created }}
      # - run: yarn config get cacheFolder
      # - run: yarn install --check-cache --inline-builds
      - run: yarn install --immutable --immutable-cache --check-cache --inline-builds
        # if: ${{ steps.release.outputs.release_created }}
      - run: yarn build
        if: ${{ steps.release.outputs.release_created }}
      - run: yarn npm whoami --scope monerium
      # - run: yarn npm publish
      # env:
      # NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      # if: ${{ steps.release.outputs.release_created }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
  echo:
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ needs.release-please.outputs.release_created || false }}'
  deploy-static:
    name: Trigger static pages deploy
    needs: [release-please]
    uses: "./.github/workflows/pages.yml"
    with:
      release_created: ${{ needs.release-please.outputs.release_created || 'false' }}
    secrets: inherit
