name: Release Please

on:
  push:
    branches:
      - main
jobs:
  release-please:
    name: "Create release"
    runs-on: ubuntu-latest
    steps:
      - uses: google-github-actions/release-please-action@v3
        id: release
        with:
          release-type: node
          package-name: sdk
          pull-request-header: "Monerium SDK release :rocket:"
          prerelease: true
          changelog-types: '[{"type":"feat","section":"Features","hidden":false},{"type":"fix","section":"Bug Fixes","hidden":false},{"type":"chore","section":"Miscellaneous","hidden":false},{ "type": "revert", "section": "Reverts", "hidden": false }, {"type":"docs","section":"Documentation","hidden":false}]'
      # The logic below handles the npm publication:
      - uses: actions/checkout@v3
        # these if statements ensure that a publication only occurs when
        # a new release is created:
        if: ${{ steps.release.outputs.release_created }}
      - name: Yarn install
        run: yarn install --immutable --immutable-cache
        # for security reasons, use --check-cache if accepting PRs from third-parties.
        if: ${{ steps.release.outputs.release_created }}
      - name: Publish NPM package ${{ steps.release.outputs.tag_name }}
        run: yarn npm publish
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
        if: ${{ steps.release.outputs.release_created }}
      - name: Build documentation
        run: yarn docs
        if: ${{ steps.release.outputs.release_created }}
      - name: Archive static artifacts
        run: tar -cvf static.tar static
        shell: bash
        if: ${{ steps.release.outputs.release_created }}
      - name: Upload static artifacts
        uses: actions/upload-artifact@v3
        with:
          name: static-artifacts
          path: static.tar
        if: ${{ steps.release.outputs.release_created }}
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
      tag_name: ${{ steps.release.outputs.tag_name }}
  echo:
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      - name: Debug
        run: |
          echo '${{ needs.release-please.outputs.release_created || false }}'
          echo '${{ needs.release-please.outputs.tag_name }}'

  deploy-static:
    name: Trigger static pages deploy
    needs: [release-please]
    uses: "./.github/workflows/pages.yml"
    with:
      release_created: ${{ needs.release-please.outputs.release_created || 'false' }}
    secrets: inherit
