name: Release Please

on:
  push:
    branches:
      - ci-test
jobs:
  release-please:
    name: "Create release"
    runs-on: ubuntu-latest
    steps:
      - run: yarn npm whoami --scope monerium
    outputs:
      release_created: ${{ steps.release.outputs.release_created }}
  echo:
    needs: [release-please]
    runs-on: ubuntu-latest
    steps:
      - run: echo '${{ needs.release-please.outputs.release_created || false }}'
  deploy-static:
    name: Trigger static pages deploy
    needs: [release-please]
    uses: "./.github/workflows/pages.yml"
    with:
      release_created: ${{ needs.release-please.outputs.release_created || 'false' }}
    secrets: inherit
